pustinek/dogecraft-wiki

- _includes/survival/Commands.md
- _includes/survival/commands.md
could be on the same page as the ore and claiming land but under it . unsure if we would want to make Res' its own section or not.. but since i've just listed the commands I felt it was better to do it this way...
> New Commands page for wiki

- _includes/rules/general.md
took out the double text and spaced the spam section ( ironic )
> updated general chat rules

- _includes/survival/commands.md
2 formatting issues under mcmmo commands
> minor updates

- _includes/rules/common_sense.md
added rule about inactivity and about ban evasion under alts
> added rule for niko

- _includes/rules/general.md
> discord rules added

- _includes/staff/about.md
Added and Moved around the descriptions a little =)
> Reorganized data

- _includes/rules/general.md
> added rule

- _includes/rules/common_sense.md
moving specific survival rules to the survival section
> moving things

- _includes/survival/survival_rules.md
moved rules from general rules to more specifically the survival section
> new file survival_rules

- _data/servers.yml
added page to survival for the rules. updated the descriptions
> added new page

- _includes/skyblock/started.md
> updated page

- _includes/survival/survival_rules.md
via nikos request for lag machine rules
> updated rules

- _includes/rules/general.md
added more annoying text rules because of max :/
> rule update

- _includes/rules/common_sense.md
updated rule on afking for extended periods of time
> added in afk rule

- _includes/rules/general.md
English in main chat rule added
> updated general rules

- _includes/survival/claiming_land.md
> updating land claim

- _includes/staff/about.md
updated staff listing to the current list
> updating staff list

- _includes/survival/custom_ores.md
> update for custom ores

- _includes/survival/commands.md
now includes hvote and a few updates
> updated command list

- _includes/survival/survival_rules.md
reduced words for easier skimming
> updated survival rules

- _includes/slimefun/index.md
> slimefun update

- _includes/slimefun/index.md
basic rules update with note about machines more to come later
> updating slimefun

- _includes/staff/about.md
reflects new staff added and new role changes
> updated staff listing

- _includes/rules/general.md
minor change to reflex multiple server chats
> updated rule 14

- _includes/staff/about.md
> updated listing

- _includes/survival/survival_rules.md
as per niko updated the afk section
> updated afk rules

- _includes/staff/about.md
included past builders and their projects for a little more recognition
> updated staff section

- _includes/slimefun/index.md
> updated as per niko

- _includes/rules/common_sense.md
> updated wording

- _includes/rules/punishment_guidelines.md
> updated mutes

- _includes/staff/about.md
> updated list
